### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

### ISSUE THREAD

**Issue by blindfuzzy** [sensepost/autoDANE#1]
Getting this error on install AND when running autoDANE: "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)"

**Comment by blindfuzzy** [comment]
This was a MySQL issue not an issue with autoDANE.

**Comment by danegoodwin** [comment]
Hey Patrick

For the sake of completeness, and to help out anyone else who has the same issue:
This error means that the MySql service isn't running, and needs to be started manually.

The install script tries to start it, but will be unable to if it's run by a user without the right privileges.
If you run into this, you'll also need to create the autodane database after running ./install. You can do this by simply running the following two commands in the autodane folder:

sudo service mysql start
mysql < createdb.sql
